### ISSUE TITLE
make cmake work

### ISSUE THREAD

**Issue by cvvergara** [prakashupes/pgrouting#2]
after doing:
```
mkdir build
cd build
```
the following must work
```
cmake ..
```

**Comment by prakashupes** [comment]
cmake .. worked

**Comment by cvvergara** [comment]
Additionally to build documentation the following must work:
```
cmake -DDOC_USE_BOOTSTRAP=ON -DWITH_DOC=ON -DBUILD_DOXY=ON  -DBUILD_LATEX=OFF  ..

**Comment by prakashupes** [comment]
Output is 
 Could NOT find Sphinx.

**Comment by cvvergara** [comment]
Additionally to be able to do debugging the following must work
```
## in build directory
rm -rf *
cmake -DPOSTGRESQL_BIN=/usr/lib/postgresql/$PGSQL_VER/bin -DDOC_USE_BOOTSTRAP=ON -DWITH_DOC=ON -DBUILD_DOXY=ON  -DBUILD_LATEX=OFF  -DCMAKE_BUILD_TYPE=Debug ..
```

**Comment by prakashupes** [comment]
All the commands you have mentioned have worked. And also
 tools/testers/doc_queries_generator.pl
Pass all the test cases.
![Screenshot from 2020-01-26 00-40-53](https://user-images.githubusercontent.com/44925217/73126108-bf1a2600-3fd4-11ea-8367-db716c67684e.png)

**Comment by prakashupes** [comment]
Sample output is mentioned

**Comment by prakashupes** [comment]
@cvvergara please review this

**Comment by prakashupes** [comment]
@cvvergara 
``` tools/testers/doc_queries_generator.pl ```
When we run this command in LINUX OS then it is required to have a database and user in postgresql with the same name as LINUX user.
So can I write a document on it and will you please merge in main repo.

**Comment by prakashupes** [comment]
@cvvergara

**Comment by prakashupes** [comment]
@prakashupes

**Comment by prakashupes** [comment]
@prakashupes  check

**Comment by cvvergara** [comment]
Testing
```
cd build
rm -rf *
cmake -DCMAKE_BUILD_TYPE=Debug ..
```
Post output on next comment

**Comment by prakashupes** [comment]
`-- CMAKE_BUILD_TYPE Debug
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/prakash/Github/pgrouting/cmake'
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Using  -std=c++11.
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/10/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 10.11 (Ubuntu 10.11-1.pgdg18.04+1)
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql/10/server
-- POSTGRESQL_LIBRARIES: /usr/lib/x86_64-linux-gnu
-- PGSQL_VERSION=1011
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.53")  
-- Boost headers were found here: /usr/include
-- Boost VERSION 1.65.1
-- BOOST_VERSION_OK 1
-- BOOST_Geometry_VERSION_OK 1
-- Performing Test C_COMPILER_SUPPORTS_FPIC
-- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prakash/Github/pgrouting/build
`

**Comment by prakashupes** [comment]
-- CMAKE_BUILD_TYPE Debug
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/prakash/Github/pgrouting/cmake'
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Using  -std=c++11.
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/10/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 10.11 (Ubuntu 10.11-1.pgdg18.04+1)
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql/10/server
-- POSTGRESQL_LIBRARIES: /usr/lib/x86_64-linux-gnu
-- PGSQL_VERSION=1011
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.53")  
-- Boost headers were found here: /usr/include
-- Boost VERSION 1.65.1
-- BOOST_VERSION_OK 1
-- BOOST_Geometry_VERSION_OK 1
-- Performing Test C_COMPILER_SUPPORTS_FPIC
-- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prakash/Github/pgrouting/build

**Comment by cvvergara** [comment]
Testing
```
cd build
rm -rf *
cmake -DDOC_USE_BOOTSTRAP=ON -DWITH_DOC=ON -DBUILD_DOXY=ON ..
 ```
Post output on next comment

**Comment by prakashupes** [comment]
-- Setting build type to 'Debug' as none was specified.
-- CMAKE_BUILD_TYPE Debug
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir='/home/prakash/Github/pgrouting/cmake'
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Using  -std=c++11.
-- Found Perl: /usr/bin/perl (found version "5.26.1") 
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/10/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 10.11 (Ubuntu 10.11-1.pgdg18.04+1)
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql/10/server
-- POSTGRESQL_LIBRARIES: /usr/lib/x86_64-linux-gnu
-- PGSQL_VERSION=1011
-- Found Boost: /usr/include (found suitable version "1.65.1", minimum required is "1.53")  
-- Boost headers were found here: /usr/include
-- Boost VERSION 1.65.1
-- BOOST_VERSION_OK 1
-- BOOST_Geometry_VERSION_OK 1
-- Performing Test C_COMPILER_SUPPORTS_FPIC
-- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Developers documentation.
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) (Required is at least version "1.7")
-- PGROUTING_DOC_TARGETS = html
-- PGROUTING_BUILD_LANGUAGES = en
-- SPHINXINTL_LANGUAGE = en
-- Checking for package 'Sphinx'
-- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
-- SPHINX_VERSION Sphinx (sphinx-build) 1.6.7
-- SPHINX_VERSION 1.6.7
-- Found Sphinx: /usr/bin/sphinx-build (Required is at least version "1.1") 
-- PGR_DOCUMENTATION_BUILD_DIR = /home/prakash/Github/pgrouting/build/doc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/prakash/Github/pgrouting/build
