### ISSUE TITLE
compile and install locally

### ISSUE THREAD

**Issue by prakashupes** [prakashupes/pgrouting#3]

**Comment by cvvergara** [comment]
```
make
sudo make install
```

**Comment by prakashupes** [comment]
sudo make install
[sudo] password for prakash: 
[  2%] Built target breadthFirstSearch
[ 16%] Built target common
[ 18%] Built target dijkstra
[ 20%] Built target allpairs
[ 21%] Built target astar
[ 24%] Built target driving_distance
[ 28%] Built target ksp
[ 31%] Built target tsp
[ 33%] Built target alpha_shape
[ 34%] Built target bdAstar
[ 36%] Built target bdDijkstra
[ 40%] Built target trsp
[ 46%] Built target max_flow
[ 48%] Built target contraction
[ 60%] Built target pickDeliver
[ 63%] Built target withPoints
[ 65%] Built target lineGraph
[ 72%] Built target components
[ 74%] Built target bellman_ford
[ 76%] Built target cpp_common
[ 77%] Built target dagShortestPath
[ 78%] Built target chinese
[ 82%] Built target spanningTree
[ 84%] Built target mincut
[ 85%] Built target version
[ 86%] Built target topologicalSort
[ 87%] Built target transitiveClosure
[ 87%] Built target pgrouting-3.0
[ 87%] Built target PGROUTING_SQL_FILE
[100%] Built target update_files
Install the project...
-- Install configuration: "Debug"
-- Installing: /usr/lib/postgresql/10/lib/libpgrouting-3.0.so
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.6.3--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.6.2--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.6.1--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.6.0--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.5.5--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.5.4--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.5.3--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.5.2--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.5.1--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.5.0--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.4.2--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.4.1--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.4.0--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.3.2--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.3.1--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.3.0--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.2.4--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.2.3--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.2.2--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.2.1--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--2.2.0--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting--3.0.0.sql
-- Installing: /usr/share/postgresql/10/extension/pgrouting.control

**Comment by cvvergara** [comment]
You can close now
