### ISSUE TITLE
test

### ISSUE THREAD

**Issue by prakashupes** [prakashupes/pgrouting#6]

**Comment by cvvergara** [comment]
```
dropdb --if-exists  ___pgr___test___
createdb   ___pgr___test___
sh ./tools/testers/pg_prove_tests.sh 
dropdb  ___pgr___test___
```

**Comment by prakashupes** [comment]
```
dropdb --if-exists  ___pgr___test___
createdb   ___pgr___test___
sh ./tools/testers/pg_prove_tests.sh 
dropdb  ___pgr___test___

**Comment by cvvergara** [comment]
please install pgtap extension

**Comment by prakashupes** [comment]
How to install pgtap extension

**Comment by prakashupes** [comment]
https://pgxn.org/dist/pgtap/doc/pgtap.html
This article dose not works

**Comment by cvvergara** [comment]
lets make sure that the extension is installed
```
createdb foo
psql foo
CREATE EXTENSION pgtap;  -- post results of this command 
\q
dropdb foo
```

**Comment by prakashupes** [comment]
```

foo=# CREATE EXTENSION pgtap
foo-# ;
CREATE EXTENSION
foo=# 
```

**Comment by cvvergara** [comment]
Maybe pg_prove is missing
https://pgtap.org/pg_prove.html

**Comment by cvvergara** [comment]
How did you install pgtap?

**Comment by prakashupes** [comment]
@cvvergara Ma'am, I think the problem that was occurring in testing is solved. After reinstalling all dependencies.

**Comment by prakashupes** [comment]
Output for: 
`sudo -u postgres bash ./tools/testers/pg_prove_tests.sh postgres 5432 Release`

**Comment by prakashupes** [comment]
`RELEASE_TYPE bRelease
-p 5432
cd ./tools/testers/
psql -f setup_db.sql
OK
../../pgtap/allpairs/compare-directed.test.sql .................................../../pgtap/allpairs/compare-directed.test.sql .................................                                                                                ../../pgtap/allpairs/compare-directed.test.sql ......................................................... ok
../../pgtap/allpairs/compare-undirected.test.sql ................................./../pgtap/allpairs/compare-undirected.test.sql ................................./../pgtap/allpairs/compare-undirected.test.sql ...............................                                                                                ../../pgtap/allpairs/compare-undirected.test.sql ....................................................... ok
../../pgtap/allpairs/floydWarshall-innerQuery.sql ................................/../pgtap/allpairs/floydWarshall-innerQuery.sql ..............................                                                                                ../../pgtap/allpairs/floydWarshall-innerQuery.sql ...................................................... ok
../../pgtap/allpairs/fw-types-check.sql ........................................../../pgtap/allpairs/fw-types-check.sql ........................................                                                                                ../../pgtap/allpairs/fw-types-check.sql ................................................................ ok
../../pgtap/allpairs/j-types-check.sql .........................................../../pgtap/allpairs/j-types-check.sql .........................................                                                                                ../../pgtap/allpairs/j-types-check.sql ................................................................. ok
../../pgtap/allpairs/johnson-innerQuery.sql ....................................../../pgtap/allpairs/johnson-innerQuery.sql ....................................                                                                                ../../pgtap/allpairs/johnson-innerQuery.sql ............................................................ ok
../../pgtap/allpairs/no_crash_test-floydWarshall.sql ............................./../pgtap/allpairs/no_crash_test-floydWarshall.sql ............................./../pgtap/allpairs/no_crash_test-floydWarshall.sql ...........................                                                                                ../../pgtap/allpairs/no_crash_test-floydWarshall.sql ................................................... ok
../../pgtap/allpairs/no_crash_test-johnson.sql .................................../../pgtap/allpairs/no_crash_test-johnson.sql .................................                                                                                ../../pgtap/allpairs/no_crash_test-johnson.sql ......................................................... ok
../../pgtap/alpha_shape/issue-544.sql ............................................/../pgtap/alpha_shape/issue-544.sql ..........................................                                                                                ../../pgtap/alpha_shape/issue-544.sql .................................................................. ok
../../pgtap/alpha_shape/no_crash_test-alphashp.sql .............................../../pgtap/alpha_shape/no_crash_test-alphashp.sql .............................                                                                                ../../pgtap/alpha_shape/no_crash_test-alphashp.sql ..................................................... ok
../../pgtap/alpha_shape/notebook-test.sql ......................................../../pgtap/alpha_shape/notebook-test.sql ......................................../../pgtap/alpha_shape/notebook-test.sql ......................................../../pgtap/alpha_shape/notebook-test.sql ......................................../../pgtap/alpha_shape/notebook-test.sql ......................................                                                                                ../../pgtap/alpha_shape/notebook-test.sql .............................................................. ok
../../pgtap/alpha_shape/s_shape-test.sql ............................................................... ok       
../../pgtap/alpha_shape/sampledata-test.sql ............................................................ ok     
../../pgtap/alpha_shape/specialCases.sql ............................................................... ok   
../../pgtap/astar/aStar-group-innerQuery.sql ........................................................... ok       
../../pgtap/astar/aStarCost-group-innerQuery.sql ....................................................... ok       
../../pgtap/astar/astar_ManyToMany-compare-dijkstra.test.sql ........................................... ok   
../../pgtap/astar/astar_ManyToOne-compare-dijkstra.test.sql ............................................ ok     
../../pgtap/astar/astar_oneToMany-compare-dijkstra.test.sql ............................................ ok     
../../pgtap/astar/astar_oneToOne-compare-dijkstra.test.sql ............................................. ok       
../../pgtap/astar/astar_oneToOne-types-check.sql ....................................................... ok       
../../pgtap/astar/no_crash_test-astar.sql .............................................................. ok     
../../pgtap/astar/no_crash_test-astarCost.sql .......................................................... ok     
../../pgtap/bdAstar/bdAstar-compare-dijkstra.sql ....................................................... ok       
../../pgtap/bdAstar/bdAstar-innerQuery.sql ............................................................. ok       
../../pgtap/bdAstar/bdAstar-parameter-types-check.sql .................................................. ok   
../../pgtap/bdAstar/bdAstar-return-types-check.sql ..................................................... ok   
../../pgtap/bdAstar/bdAstarCost-innerQuery.sql ......................................................... ok       
../../pgtap/bdAstar/bdAstarCostMatrix-innerQuery.sql ................................................... ok       
../../pgtap/bdAstar/no_crash_test-bdastar.sql .......................................................... ok     
../../pgtap/bdAstar/no_crash_test-bdastarCost.sql ...................................................... ok     
../../pgtap/bdDijkstra/bdDijkstra-compare-dijkstra.sql ................................................. ok       
../../pgtap/bdDijkstra/bdDijkstra-innerQuery.sql ....................................................... ok       
../../pgtap/bdDijkstra/bdDijkstra-types-check.sql ...................................................... ok   
../../pgtap/bdDijkstra/bdDijkstraCost-innerQuery.sql ................................................... ok       
../../pgtap/bdDijkstra/no_crash_test-bdDijkstra.sql .................................................... ok     
../../pgtap/bdDijkstra/no_crash_test-bdDijkstraCost.sql ................................................ ok     
../../pgtap/bellman_ford/bellman_ford/bellman_ford-compare-dijkstra.sql ................................ ok         
../../pgtap/bellman_ford/bellman_ford/bellman_ford-innerQuery.sql ...................................... ok       
../../pgtap/bellman_ford/bellman_ford/bellman_ford-typesCheck.sql ...................................... ok   
../../pgtap/bellman_ford/bellman_ford/bellman_ford_neg_edges-typesCheck.sql ............................ ok   
../../pgtap/bellman_ford/edwardMoore/edwardMoore-compare-dijkstra.sql .................................. ok         
../../pgtap/bellman_ford/edwardMoore/edwardMoore-innerQuery.sql ........................................ ok       
../../pgtap/bellman_ford/edwardMoore/edwardMoore-types-check.sql ....................................... ok     
../../pgtap/bellman_ford/edwardMoore/no_crash_test-edwardMoore.sql ..................................... ok     
../../pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-compare-dijkstra.sql .. ok         
../../pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-edge-cases.sql ........ ok     
../../pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-innerQuery.sql ........ ok       
../../pgtap/breadthFirstSearch/binaryBreadthFirstSearch/binaryBreadthFirstSearch-types-check.sql ....... ok     
../../pgtap/breadthFirstSearch/binaryBreadthFirstSearch/no_crash_test-binaryBreadthFirstSearch.sql ..... ok       
../../pgtap/breadthFirstSearch/breadthFirstSearch/breadthFirstSearch-edge-cases.sql .................... ok     
../../pgtap/breadthFirstSearch/breadthFirstSearch/breadthFirstSearch-innerQuery.sql .................... ok       
../../pgtap/breadthFirstSearch/breadthFirstSearch/breadthFirstSearch-types-check.sql ................... ok   
../../pgtap/breadthFirstSearch/breadthFirstSearch/no_crash_test-breadthFirstSearch.sql ................. ok     
../../pgtap/chinese/chinesePostman/innerQuery.sql ...................................................... ok     
../../pgtap/chinese/chinesePostman/types-check.sql ..................................................... ok   
../../pgtap/chinese/chinesePostmanCost/innerQuery.sql .................................................. ok     
../../pgtap/chinese/chinesePostmanCost/types-check.sql ................................................. ok   
../../pgtap/common/checkVertTab.test.sql ............................................................... ok     
../../pgtap/common/getColumnName.test.sql .............................................................. ok     
../../pgtap/common/getColumnType.test.sql .............................................................. ok     
../../pgtap/common/getTableName.test.sql ............................................................... ok     
../../pgtap/common/has_v3_signatures.sql ............................................................... ok     
../../pgtap/common/hasnt_v2_signatures.sql ............................................................. ok     
../../pgtap/common/isColumnInTable.test.sql ............................................................ ok     
../../pgtap/common/isColumnIndexed.test.sql ............................................................ ok     
../../pgtap/components/articulationPoints/innerQuery.sql ............................................... ok     
../../pgtap/components/articulationPoints/no_crash_test.sql ............................................ ok   
../../pgtap/components/biconnectedComponents/innerQuery.sql ............................................ ok     
../../pgtap/components/biconnectedComponents/no_crash_test.sql ......................................... ok   
../../pgtap/components/bridges/innerQuery.sql .......................................................... ok     
../../pgtap/components/bridges/no_crash_test.sql ....................................................... ok   
../../pgtap/components/connectedComponenes/innerQuery.sql .............................................. ok     
../../pgtap/components/connectedComponenes/no_crash_test.sql ........................................... ok   
../../pgtap/components/strongComponenets/innerQuery.sql ................................................ ok     
../../pgtap/components/strongComponenets/no_crash_test.sql ............................................. ok   
../../pgtap/contraction/combined/dijkstra-compare.sql .................................................. ok       
../../pgtap/contraction/contraction-types-check.sql .................................................... ok     
../../pgtap/contraction/contraction_cycle_directed.sql ................................................. ok     
../../pgtap/contraction/contraction_cycle_undirected.sql ............................................... ok     
../../pgtap/contraction/deadend/directed/dijkstra-compare.sql .......................................... ok       
../../pgtap/contraction/deadend/directed/directed-big-ids.sql .......................................... ok   
../../pgtap/contraction/deadend/directed/directed-deadend-cases.sql .................................... ok   
../../pgtap/contraction/deadend/directed/directed-dev-deadend.sql ...................................... ok   
../../pgtap/contraction/deadend/directed/directed-small_ids.sql ........................................ ok   
../../pgtap/contraction/deadend/directed/directed-super-big-ids.sql .................................... ok   
../../pgtap/contraction/deadend/directed/directed_dead_end.sql ......................................... ok     
../../pgtap/contraction/deadend/directed/innerQuery.sql ................................................ ok     
../../pgtap/contraction/deadend/undirected/big-ids.sql ................................................. ok   
../../pgtap/contraction/deadend/undirected/cases.sql ................................................... ok   
../../pgtap/contraction/deadend/undirected/dev-cases.sql ............................................... ok   
../../pgtap/contraction/deadend/undirected/dijkstra-compare.sql ........................................ ok       
../../pgtap/contraction/deadend/undirected/innerQuery.sql .............................................. ok     
../../pgtap/contraction/deadend/undirected/more_cases.sql .............................................. ok     
../../pgtap/contraction/deadend/undirected/small_ids.sql ............................................... ok   
../../pgtap/contraction/deadend/undirected/super_big_ids.sql ........................................... ok   
../../pgtap/contraction/issue1002/issue1002.sql ........................................................ ok   
../../pgtap/contraction/linear/directed/dijkstra-compare.sql ........................................... ok       
../../pgtap/contraction/linear/directed/directed_linear.sql ............................................ ok     
../../pgtap/contraction/linear/directed/innerQuery.sql ................................................. ok     
../../pgtap/contraction/linear/undirected/dijkstra-compare.sql ......................................... ok       
../../pgtap/contraction/linear/undirected/innerQuery.sql ............................................... ok     
../../pgtap/contraction/linear/undirected/undirected_linear.sql ........................................ ok     
../../pgtap/contraction/no_crash_test-contraction.sql .................................................. ok   
../../pgtap/costMatrix/aStarCostMatrix/innerQuery.sql .................................................. ok       
../../pgtap/costMatrix/aStarCostMatrix/no_crash_test.sql ............................................... ok     
../../pgtap/costMatrix/bdAstarCostMatrix/innerQuery.sql ................................................ ok       
../../pgtap/costMatrix/bdAstarCostMatrix/no_crash_test.sql ............................................. ok     
../../pgtap/costMatrix/bdDijkstraCostMatrix/innerQuery.sql ............................................. ok     
../../pgtap/costMatrix/bdDijkstraCostMatrix/no_crash_test.sql .......................................... ok     
../../pgtap/costMatrix/dijkstraCostMatrix/innerQuery.sql ............................................... ok     
../../pgtap/costMatrix/dijkstraCostMatrix/no_crash_test.sql ............................................ ok     
../../pgtap/costMatrix/withPointsCostMatrix/innerQuery.sql ............................................. ok     
../../pgtap/costMatrix/withPointsCostMatrix/no_crash_test.sql .......................................... ok     
../../pgtap/dagShortestPath/dagShortestPath-innerQuery.sql ............................................. ok   
../../pgtap/dagShortestPath/dagShortestPath-typesCheck.sql ............................................. ok     
../../pgtap/dijkstra/dijkstra-group-innerQuery.sql ..................................................... ok       
../../pgtap/dijkstra/dijkstra-infinity-alt-cost.test.sql ............................................... ok   
../../pgtap/dijkstra/dijkstra-infinity-cost.test.sql ................................................... ok   
../../pgtap/dijkstra/dijkstra-issue-353.test.sql ....................................................... ok   
../../pgtap/dijkstra/dijkstra-types-check.sql .......................................................... ok     
../../pgtap/dijkstra/dijkstraCost-group-innerQuery.sql ................................................. ok       
../../pgtap/dijkstra/dijkstraCost-types-check.sql ...................................................... ok     
../../pgtap/dijkstra/dijkstraVia-equivalenceDijkstra.test.sql .......................................... ok   
../../pgtap/dijkstra/dijkstraVia-innerQuery.sql ........................................................ ok     
../../pgtap/dijkstra/dijkstraVia-types-check.sql ....................................................... ok     
../../pgtap/dijkstra/no_crash_test-dijkstra.sql ........................................................ ok     
../../pgtap/dijkstra/no_crash_test-dijkstraCost.sql .................................................... ok     
../../pgtap/dijkstra/no_crash_test-dijkstraVia.sql ..................................................... ok     
../../pgtap/dijkstra/oneToOne_equiv_manyToMany.test.sql ................................................ ok   
../../pgtap/dijkstra/oneToOne_equiv_manyToOne.test.sql ................................................. ok     
../../pgtap/dijkstra/oneToOne_equiv_oneToMany.test.sql ................................................. ok     
../../pgtap/dijkstra/zero_one_edge_-1_rev.test.sql ..................................................... ok     
../../pgtap/dijkstra/zero_one_edge_has_rev.test.sql .................................................... ok     
../../pgtap/dijkstra/zero_one_edge_no_rev.test.sql ..................................................... ok     
../../pgtap/driving_distance/dijkstraDD-innerQuery.sql ................................................. ok       
../../pgtap/driving_distance/issue-519.sql ............................................................. ok   
../../pgtap/driving_distance/issue1152.sql ............................................................. ok     
../../pgtap/driving_distance/no_crash_test-drivingDistance.sql ......................................... ok     
../../pgtap/driving_distance/no_crash_test-withPointsDD.sql ............................................ ok     
../../pgtap/driving_distance/withPointsDD-group-innerQuery.sql ......................................... ok       
../../pgtap/ksp/issue1010.sql .......................................................................... ok   
../../pgtap/ksp/ksp-innerQuery.sql ..................................................................... ok     
../../pgtap/ksp/ksp-v3-1route.test.sql ................................................................. ok   
../../pgtap/ksp/no_crash_test-ksp.sql .................................................................. ok     
../../pgtap/ksp/no_crash_test-withPointsKSP.sql ........................................................ ok     
../../pgtap/ksp/parallel-v2.test.sql ................................................................... ok   
../../pgtap/ksp/parallel.test.sql ...................................................................... ok   
../../pgtap/ksp/tr_compare-dijkstra.sql ................................................................ ok         
../../pgtap/ksp/tr_custom.sql .......................................................................... ok   
../../pgtap/ksp/tr_empty_set_NO_default_strict.sql ..................................................... ok     
../../pgtap/ksp/tr_empty_set_default_strict.sql ........................................................ ok     
../../pgtap/ksp/tr_innerQuery.sql ...................................................................... ok   
../../pgtap/ksp/tr_typesCheck.sql ...................................................................... ok   
../../pgtap/ksp/withPointsKSP-innerQuery.sql ........................................................... ok     
../../pgtap/lineGraph/lineGraph/innerQuery.sql ......................................................... ok       
../../pgtap/lineGraph/lineGraph/lineGraph-typesCheck.sql ............................................... ok   
../../pgtap/lineGraph/lineGraph/no_crash_test-lineGraph.sql ............................................ ok   
../../pgtap/lineGraph/lineGraph/no_crash_test.sql ...................................................... ok   
../../pgtap/lineGraph/lineGraphFull/innerQuery.sql ..................................................... ok     
../../pgtap/lineGraph/lineGraphFull/lineGraphFull-reverse_cost_equivalence.sql ......................... ok   
../../pgtap/lineGraph/lineGraphFull/lineGraphFull-typesCheck.sql ....................................... ok   
../../pgtap/lineGraph/lineGraphFull/lineGraphFull_dijkstra_equivalence.sql ............................. ok   
../../pgtap/lineGraph/lineGraphFull/lineGraphFull_original_edge_check.sql .............................. ok   
../../pgtap/lineGraph/lineGraphFull/lineGraphFull_original_vertex_mapping.sql .......................... ok   
../../pgtap/max_flow/boykovKolmogorov-innerQuery.sql ................................................... ok       
../../pgtap/max_flow/boykovKolmogorov-types-check.sql .................................................. ok     
../../pgtap/max_flow/edgedisjointpaths-group-innerQuery.sql ............................................ ok       
../../pgtap/max_flow/edgedisjointpaths-types-check.sql ................................................. ok     
../../pgtap/max_flow/edmondsKarp-innerQuery.sql ........................................................ ok       
../../pgtap/max_flow/edmondsKarp-types-check.sql ....................................................... ok     
../../pgtap/max_flow/internet_example.sql .............................................................. ok   
../../pgtap/max_flow/maxCardinalityMatch-innerQuery.sql ................................................ ok       
../../pgtap/max_flow/maxCardinalityMatch-types-check.sql ............................................... ok   
../../pgtap/max_flow/maxFlow/maxflow-group-innerQuery.sql .............................................. ok       
../../pgtap/max_flow/maxFlow/maxflow-types-check.sql ................................................... ok     
../../pgtap/max_flow/maxFlow/no_crash_test-maxFlow.sql ................................................. ok     
../../pgtap/max_flow/maxFlowMinCost/maxFlowMinCost-innerQuery.sql ...................................... ok       
../../pgtap/max_flow/maxFlowMinCost/maxFlowMinCost-types-check.sql ..................................... ok     
../../pgtap/max_flow/maxFlowMinCost/maxFlowMinCost_Cost-innerquery.sql ................................. ok       
../../pgtap/max_flow/maxFlowMinCost/maxFlowMinCost_Cost-types-check.sql ................................ ok     
../../pgtap/max_flow/no_crash_test-boykovKolmogorov.sql ................................................ ok     
../../pgtap/max_flow/no_crash_test-edgeDisjointPaths.sql ............................................... ok     
../../pgtap/max_flow/no_crash_test-edmondsKarp.sql ..................................................... ok     
../../pgtap/max_flow/no_crash_test-maxCardinalityMatch.sql ............................................. ok   
../../pgtap/max_flow/no_crash_test-pushRelabel.sql ..................................................... ok     
../../pgtap/max_flow/pushRelabel-innerQuery.sql ........................................................ ok       
../../pgtap/max_flow/pushRelabel-types-check.sql ....................................................... ok     
../../pgtap/mincut/compare.test.sql .................................................................... ok   
../../pgtap/mincut/stoerWagner-innerQuery.sql .......................................................... ok     
../../pgtap/mincut/stoerWagner-types-check.sql ......................................................... ok   
../../pgtap/pickDeliver/order_id_is_neg1.sql ........................................................... ok   
../../pgtap/pickDeliver/pickDeliver-VS-pickDeliverEuclidean.sql ........................................ ok   
../../pgtap/pickDeliver/pickDeliver/innerQuery.sql ..................................................... ok     
../../pgtap/pickDeliver/pickDeliver/types_check.sql .................................................... ok   
../../pgtap/pickDeliver/pickDeliverEuclidean/innerQuery.sql ............................................ ok       
../../pgtap/pickDeliver/pickDeliverEuclidean/types_check.sql ........................................... ok   
../../pgtap/pickDeliver/wrong_data_pickDeliverEuclidean.sql ............................................ ok     
../../pgtap/spanningTree/compare-prim-kruskal.sql ...................................................... ok   
../../pgtap/spanningTree/compare-primBFS-kruskalBFS.sql ................................................ ok     
../../pgtap/spanningTree/compare-primDD-kruskalDD.sql .................................................. ok     
../../pgtap/spanningTree/compare-primDFS-kruskalDFS.sql ................................................ ok     
../../pgtap/spanningTree/kruskal/kruskal/kruskal-edge-cases.sql ........................................ ok   
../../pgtap/spanningTree/kruskal/kruskal/kruskal-innerQuery.sql ........................................ ok     
../../pgtap/spanningTree/kruskal/kruskal/kruskal-types-check.sql ....................................... ok   
../../pgtap/spanningTree/kruskal/kruskal/no_crash_test-kruskal.sql ..................................... ok   
../../pgtap/spanningTree/kruskal/kruskalBFS/kruskalBFS-edge-cases.sql .................................. ok     
../../pgtap/spanningTree/kruskal/kruskalBFS/kruskalBFS-innerQuery.sql .................................. ok     
../../pgtap/spanningTree/kruskal/kruskalBFS/kruskalBFS-types-check.sql ................................. ok   
../../pgtap/spanningTree/kruskal/kruskalBFS/no_crash_test-kruskalBFS.sql ............................... ok     
../../pgtap/spanningTree/kruskal/kruskalDD/kruskalDD-edge-cases.sql .................................... ok   
../../pgtap/spanningTree/kruskal/kruskalDD/kruskalDD-innerQuery.sql .................................... ok     
../../pgtap/spanningTree/kruskal/kruskalDD/kruskalDD-types-check.sql ................................... ok     
../../pgtap/spanningTree/kruskal/kruskalDD/no_crash_test-kruskalDD.sql ................................. ok       
../../pgtap/spanningTree/kruskal/kruskalDFS/kruskalDFS-edge-cases.sql .................................. ok     
../../pgtap/spanningTree/kruskal/kruskalDFS/kruskalDFS-innerQuery.sql .................................. ok     
../../pgtap/spanningTree/kruskal/kruskalDFS/kruskalDFS-types-check.sql ................................. ok   
../../pgtap/spanningTree/kruskal/kruskalDFS/no_crash_test-kruskalDFS.sql ............................... ok     
../../pgtap/spanningTree/prim/prim/no_crash_test-prim.sql .............................................. ok   
../../pgtap/spanningTree/prim/prim/prim-edge-cases.sql ................................................. ok   
../../pgtap/spanningTree/prim/prim/prim-innerQuery.sql ................................................. ok     
../../pgtap/spanningTree/prim/prim/prim-types-check.sql ................................................ ok   
../../pgtap/spanningTree/prim/primBFS/no_crash_test-primBFS.sql ........................................ ok     
../../pgtap/spanningTree/prim/primBFS/primBFS-edge-cases.sql ........................................... ok     
../../pgtap/spanningTree/prim/primBFS/primBFS-innerQuery.sql ........................................... ok     
../../pgtap/spanningTree/prim/primBFS/primBFS-types-check.sql .......................................... ok   
../../pgtap/spanningTree/prim/primDD/no_crash_test-primDD.sql .......................................... ok       
../../pgtap/spanningTree/prim/primDD/primDD-edge-cases.sql ............................................. ok   
../../pgtap/spanningTree/prim/primDD/primDD-innerQuery.sql ............................................. ok     
../../pgtap/spanningTree/prim/primDD/primDD-types-check.sql ............................................ ok     
../../pgtap/spanningTree/prim/primDFS/no_crash_test-primDFS.sql ........................................ ok     
../../pgtap/spanningTree/prim/primDFS/primDFS-edge-cases.sql ........................................... ok     
../../pgtap/spanningTree/prim/primDFS/primDFS-innerQuery.sql ........................................... ok     
../../pgtap/spanningTree/prim/primDFS/primDFS-types-check.sql .......................................... ok   
../../pgtap/topologicalSort/no_crash_test-topologicalSort.sql .......................................... ok   
../../pgtap/topologicalSort/topologicalSort-innerQuery.sql ............................................. ok   
../../pgtap/topology/analyzeGraph.test.sql ............................................................. ok   
../../pgtap/topology/analyzeGraph/issue1311.sql ........................................................ ok   
../../pgtap/topology/analyzeOneWay.test.sql ............................................................ ok   
../../pgtap/topology/createTopology.test.sql ........................................................... ok       
../../pgtap/topology/createVerticesTable.test.sql ...................................................... ok     
../../pgtap/topology/createVerticesTable/issue1309.sql ................................................. ok   
../../pgtap/topology/extractVertices/edge-cases.sql .................................................... ok     
../../pgtap/topology/extractVertices/innerQuery.sql .................................................... ok     
../../pgtap/topology/extractVertices/no_crash_test.sql ................................................. ok     
../../pgtap/topology/extractVertices/types-check.sql ................................................... ok   
../../pgtap/topology/incrementalCreateTopology.test.sql ................................................ ok     
../../pgtap/topology/issue-1009.sql .................................................................... ok     
../../pgtap/topology/issue-1074.sql .................................................................... ok     
../../pgtap/topology/issue-1336.sql .................................................................... ok     
../../pgtap/topology/nodeNetwork.test.sql .............................................................. ok     
../../pgtap/transitiveClosure/no_crash_test-transitiveClosure.sql ...................................... ok   
../../pgtap/transitiveClosure/transitiveClosure-innerQuery.sql ......................................... ok   
../../pgtap/trsp/blank-restrictions-compare-dijkstra.test.sql .......................................... ok         
../../pgtap/trsp/emptyset-from-i-to-i.test.sql ......................................................... ok       
../../pgtap/trsp/from1to3.test.sql ..................................................................... ok   
../../pgtap/trsp/from3to4-directed.test.sql ............................................................ ok   
../../pgtap/trsp/no-restrictions-compare-dijkstra-directed.test.sql .................................... ok       
../../pgtap/trsp/no-restrictions-compare-dijkstra-undirected.test.sql .................................. ok       
../../pgtap/trsp/no_crash_test-trsp-int-flt.sql ........................................................ ok     
../../pgtap/trsp/no_crash_test-trsp-int-int.sql ........................................................ ok     
../../pgtap/trsp/no_crash_test-trsp-viaE.sql ........................................................... ok     
../../pgtap/trsp/no_crash_test-trsp-viaV.sql ........................................................... ok     
../../pgtap/trsp/trsp-any-00.test.sql .................................................................. ok   
../../pgtap/trsp/trsp-any-01.test.sql .................................................................. ok   
../../pgtap/trsp/trsp-issue244.test.sql ................................................................ ok   
../../pgtap/trsp/trsp/innerQuery.sql ................................................................... ok       
../../pgtap/trsp/trspViaEdges/innerQuery.sql ........................................................... ok       
../../pgtap/trsp/trspViaVertices/innerQuery.sql ........................................................ ok       
../../pgtap/trsp/viaV-no-restrictions-compare-dijkstra-directed.test.sql ............................... ok         
../../pgtap/trsp/viaV-no-restrictions-compare-dijkstra-undirected.test.sql ............................. ok         
../../pgtap/tsp/TSPeuclidean/illegal_values.sql ........................................................ ok   
../../pgtap/tsp/TSPeuclidean/innerQuery.sql ............................................................ ok     
../../pgtap/tsp/TSPeuclidean/no_crash_test.sql ......................................................... ok   
../../pgtap/tsp/TSPeuclidean/types_check.sql ........................................................... ok   
../../pgtap/tsp/no_crash_test-tsp.sql .................................................................. ok   
../../pgtap/tsp/pgr_TSP_types_check.sql ................................................................ ok     
../../pgtap/version/full_version.sql ................................................................... ok   
../../pgtap/version/version.sql ........................................................................ ok   
../../pgtap/vrp_basic/no_crash_test-vrpOneDepot.sql .................................................... ok     
../../pgtap/withPoints/issue979DD.sql .................................................................. ok   
../../pgtap/withPoints/many_to_many_eq_one_to_one_withPoint.test.sql ................................... ok     
../../pgtap/withPoints/many_to_one_eq_one_to_one_withPoint.test.sql .................................... ok   
../../pgtap/withPoints/no_crash_test-withPoints.sql .................................................... ok     
../../pgtap/withPoints/no_crash_test-withPointsCost.sql ................................................ ok     
../../pgtap/withPoints/one_to_many_eq_one_to_one_withPoint.test.sql .................................... ok   
../../pgtap/withPoints/one_to_many_withPoint.test.sql .................................................. ok   
../../pgtap/withPoints/one_to_one_withPoint.test.sql ................................................... ok   
../../pgtap/withPoints/undirected_equalityDD.sql ....................................................... ok   
../../pgtap/withPoints/undirected_equalityWPDijkstra.sql ............................................... ok     
../../pgtap/withPoints/withPoints-group-innerQuery.sql ................................................. ok       
../../pgtap/withPoints/withPointsCost-group-innerQuery.sql ............................................. ok       
All tests successful.

Test Summary Report
-------------------
../../pgtap/alpha_shape/s_shape-test.sql                                                             (Wstat: 0 Tests: 167 Failed: 0)
  TODO passed:   95
../../pgtap/topology/createVerticesTable.test.sql                                                    (Wstat: 0 Tests: 95 Failed: 0)
  TODO passed:   33-35
../../pgtap/trsp/trsp/innerQuery.sql                                                                 (Wstat: 0 Tests: 162 Failed: 0)
  TODO passed:   4-6, 10-12, 16-18, 34-36, 40-42, 46-48
                58-60, 64-66, 70-72, 88-90, 94-96, 100-102
                112-114, 118-120, 124-126, 142-144, 148-150
                154-156
../../pgtap/trsp/trspViaEdges/innerQuery.sql                                                         (Wstat: 0 Tests: 162 Failed: 0)
  TODO passed:   4-6, 10-12, 16-18, 34-36, 40-42, 46-48
                58-60, 64-66, 70-72, 88-90, 94-96, 100-102
                112-114, 118-120, 124-126, 142-144, 148-150
                154-156
../../pgtap/trsp/trspViaVertices/innerQuery.sql                                                      (Wstat: 0 Tests: 162 Failed: 0)
  TODO passed:   4-6, 10-12, 16-18, 34-36, 40-42, 46-48
                58-60, 64-66, 70-72, 88-90, 94-96, 100-102
                112-114, 118-120, 124-126, 142-144, 148-150
                154-156
Files=292, Tests=30878, 504 wallclock secs ( 3.34 usr  0.58 sys + 15.86 cusr  3.86 csys = 23.64 CPU)
Result: PASS`

**Comment by prakashupes** [comment]
I have referred from [link](https://github.com/pgRouting/pgrouting/runs/387425412)

**Comment by cvvergara** [comment]
OK, you got it working
close this issue
